### ISSUE TITLE
kubestate not reaching kube-state-metrics service

### ISSUE THREAD

**Issue by krupnikola** [paulwelch/kubestate#2]
hi, I have the problem with running the tool, although I have multiple running clusters on GCP, all of them have kube-state-metrics:latest running and kubectl is working normaly.

```
(⎈ |gke_nik-testing-32508015_europe-west1-b_cs-systems-nik-infra-test:system) ~  kubectl get pods | grep kube
kube-state-metrics-6445cdb5c7-89w7b      2/2     Running   0          4m41s

(⎈ |gke_nik-testing-32508015_europe-west1-b_cs-systems-nik-infra-test:system) ~  ./kubestate get
Error: kube-state-metrics service not found. See https://github.com/kubernetes/kube-state-metrics
```

Any advice on what I'm doing wrong? 
Thanks

**Comment by paulwelch** [comment]
Hi Nikola - Thanks for trying out my kubestate project!  

Looking at the code where that message happens give me a couple ideas.  Can you confirm what namespace kube-state-metrics is running in and possibly try 'kubectl get svc --all-namespaces | grep kube-state-metrics'?

Thanks!

**Comment by krupnikola** [comment]
here is the output 
```
(⎈ |gke_nik-testing-32508015_europe-west1-b_cs-systems-nik-infra-test:system) ~  kubectl get svc --all-namespaces | grep kube-state-metrics
system        kube-state-metrics     ClusterIP   10.25.12.222   <none>        8080/TCP,8081/TCP   126d
```

**Comment by paulwelch** [comment]
I see the problem.  It has to do with the namespace in the service endpoint validation code.  I'll work on a patch to fix it, but it may take some time given my schedule for the next few weeks.  In the mean time, if you move the kube-state-metrics service into namespace "kube-system" instead of its current "system" namespace, it should work.

If you run into more issues, please add them.  This is a first pass (v0.0.2) at the tool and it will benefit from your feedback.

**Comment by paulwelch** [comment]
The code has been refactored to reach the kube-state-metrics endpoint and checked into the dev branch.  However, there is a bigger problem, see: https://github.com/paulwelch/kubestate/issues/3

The kubestate tool will not work until either: 1) kube-state-metrics supports protobuf again; or 2) kubestate is refactored to deserialize plain text.

Closing this issue and will incorporate into the next release, which will be after issue #3 resolution.
